FIND_PATH(TIDY_INCLUDE_DIR NAMES tidy.h)

FIND_LIBRARY(TIDY_LIBRARIES NAMES tidy)


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Tidy DEFAULT_MSG TIDY_INCLUDE_DIR TIDY_LIBRARIES)
